-- 2.Lookup the Customerfullname from the Customer and Unit Price from Product sheet to Sales sheet.

with sales as(SELECT * FROM adventurework.factinternetsales
union 
select * from adventurework.fact_internet_sales_new),
customer as(select CustomerKey, concat(FirstName," ",MiddleName, " ",LastName) as customerfullname from dimcustomer),
salesProduct as(select
sales.ProductKey as product_key,
OrderDateKey,
DueDateKey,
ShipDateKey,
CustomerKey,
PromotionKey,
CurrencyKey,
SalesTerritoryKey,
SalesOrderNumber,
SalesOrderLineNumber,
RevisionNumber,
OrderQuantity,
-- UnitPrice,
ExtendedAmount,
UnitPriceDiscountPct,
DiscountAmount,
ProductStandardCost,
TotalProductCost,
SalesAmount,
TaxAmt,
Freight,
CarrierTrackingNumber,
CustomerPONumber,
OrderDate,
DueDate,
ShipDate,
'Unit price' as unit_price from sales inner join dimproduct on sales.ProductKey = dimproduct.ProductKey)

select 
product_key,
OrderDateKey,
DueDateKey,
ShipDateKey,
salesProduct.CustomerKey as customer_key,
PromotionKey,
CurrencyKey,
SalesTerritoryKey,
SalesOrderNumber,
SalesOrderLineNumber,
RevisionNumber,
OrderQuantity,
-- UnitPrice,
ExtendedAmount,
UnitPriceDiscountPct,
DiscountAmount,
ProductStandardCost,
TotalProductCost,
SalesAmount,
TaxAmt,
Freight,
CarrierTrackingNumber,
CustomerPONumber,
OrderDate,
DueDate,
ShipDate,
unit_price,
customerfullname from salesProduct inner join customer on salesProduct.CustomerKey = customer.CustomerKey;